encoding: utf-8
name: Lunch with Lucy
title: Lunch with Lucy

sass:
  sass_dir: _sass
  style: :compressed


baseurl: /lunchwithlucy/

plugins:
  - jekyll-compress-images

imageoptim:
  pngout: false
  svgo: true
  verbose: false

compress_images:
  images_path: "assets/images/**/*.{gif,png,jpg,jpeg,svg}"
